Add the ability to mock any 'taskFor' targets
ember-cli/ember-cli-internal-test-helpers pull request #29
Opened 2016-08-30 13:30 UTC by sivakumar-kailasam

`disable-npm-on-blueprint` helper nows uses this internally. Added tests for the existing helper & the new one. Fixes #22

2016-08-30 13:41 UTC, sivakumar-kailasam commented
@Turbo87 Although ember-cli-blueprint-test-helpers's [package.json](https://github.com/ember-cli/ember-cli-blueprint-test-helpers/blob/master/package.json#L28) got the version range covered, would it be ok to update a patch version there as well?

2016-09-06 15:28 UTC, sivakumar-kailasam commented
@Turbo87 any improvements required on this?

2016-09-07 07:54 UTC, Turbo87 commented
@sivakumar-kailasam looks quite good! I have one small issue though. In the current state the list of tasks to ignore is somewhat fixed. In other words: the list has to be provided once `disableTasks()` is called. `disableNPM()` is called by the blueprint helpers though and that call can't be changed from the outside, so if you want to disable e.g. `bower-install` too you can't change the list of ignored tasks anymore.

2016-11-29 14:07 UTC, sivakumar-kailasam commented
@Turbo87 hope the latest changes I made were what you mentioned.

2017-01-20 23:35 UTC, simonihmig commented
Just ran into the issue #22, not being able to test blueprints that use `addBowerPackageToProject`.

So guys, what's the state of this? @sivakumar-kailasam @Turbo87

2017-01-21 11:27 UTC, sivakumar-kailasam commented
@simonihmig waiting on a review from @Turbo87

2017-01-22 12:02 UTC, simonihmig commented
@Turbo87 Any updates on this? 

*(btw, this is directly related to Sass support in ember-bootstrap, currently Blueprints are not testable because of this 😉)*

2017-01-24 07:57 UTC, Turbo87 requested changes

2017-01-24 07:57 UTC, Turbo87 commented on lib/helpers/acceptance.js
> -var conf              = require('./conf');
@sivakumar-kailasam these seem like unrelated changes. could you rebase this branch on top of the current `master`? sorry for the review delay, forgot about the PR... 😞

2017-01-24 12:24 UTC, sivakumar-kailasam commented
@Turbo87 Np, glad to land this. Rebased on latest.

2017-01-26 13:14 UTC, Turbo87 requested changes

2017-01-26 13:14 UTC, Turbo87 commented on lib/helpers/mock-blueprint-task-for.js
> +      console.log(tasksToMock, taskName);
@sivakumar-kailasam `console.log` probably shouldn't be in here, right?

2017-01-26 13:14 UTC, Turbo87 commented on lib/helpers/mock-blueprint-task-for.js
> +var tasksToMock = ['npm-install'];
how do you modify that array from the outside?

2017-01-27 09:28 UTC, sivakumar-kailasam commented
Looks like a commit got lost when I did a force rebase. Fixed it now.

On Thu, Jan 26, 2017 at 6:44 PM Tobias Bieniek <notifications@github.com>
wrote:

> *@Turbo87* requested changes on this pull request.
> ------------------------------
>
> In lib/helpers/mock-blueprint-task-for.js
> <https://github.com/ember-cli/ember-cli-internal-test-helpers/pull/29#pullrequestreview-18617173>
> :
>
> > @@ -0,0 +1,28 @@
> +'use strict';
> +var originalTaskForFn;
> +var Promise     = require('rsvp');
> +var tasksToMock = ['npm-install'];
> +
> +module.exports = {
> +  disableTasks: function(Blueprint) {
> +    originalTaskForFn = Blueprint.prototype.taskFor;
> +
> +    Blueprint.prototype.taskFor = function(taskName) {
> +      console.log(tasksToMock, taskName);
>
> @sivakumar-kailasam <https://github.com/sivakumar-kailasam> console.log
> probably shouldn't be in here, right?
> ------------------------------
>
> In lib/helpers/mock-blueprint-task-for.js
> <https://github.com/ember-cli/ember-cli-internal-test-helpers/pull/29#pullrequestreview-18617173>
> :
>
> > @@ -0,0 +1,28 @@
> +'use strict';
> +var originalTaskForFn;
> +var Promise     = require('rsvp');
> +var tasksToMock = ['npm-install'];
>
> how do you modify that array from the outside?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ember-cli/ember-cli-internal-test-helpers/pull/29#pullrequestreview-18617173>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAk31bwMNucs3qIS9tGDYLCcLEHqYbulks5rWJwbgaJpZM4JwhwK>
> .
>
-- 

Regards,
Siva

2017-01-27 16:01 UTC, Turbo87 commented
@ember-cli/core would be great to have a second pair of eyes on this before merging.

2017-01-27 18:36 UTC, kellyselden approved these changes
LGTM

2017-01-29 10:30 UTC, Turbo87 approved these changes

2017-01-29 10:30 UTC, merged

2017-01-29 10:30 UTC, Turbo87 commented
thanks @sivakumar-kailasam!

2017-01-29 14:32 UTC, simonihmig commented
Thanks for the work here! Could we get a (patch) release with this?

2017-01-29 17:06 UTC, sivakumar-kailasam commented
@Turbo87 an updated release of [ember-cli-blueprint-test-helpers](https://github.com/ember-cli/ember-cli-blueprint-test-helpers) would be helpful as well

2017-01-29 19:03 UTC, Turbo87 commented
@sivakumar-kailasam @simonihmig actually I don't seem to have the necessary permissions to publish this to NPM, but once #34 this will hopefully be easier :)

2017-02-08 07:08 UTC, sivakumar-kailasam commented
@Turbo87 now that #34 has landed, can you please create a tag?

2017-02-08 10:32 UTC, Turbo87 commented
@sivakumar-kailasam done, thanks for the reminder